name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run: dotnet build Fxplorer_www.sln
    - name: Documentation
      run: dotnet fsdocs build